"""initial schema

Revision ID: 26587d980acc
Revises: 
Create Date: 2026-05-21 03:52:07.803850
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26587d980acc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('action_proposals',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('proposed_content', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_proposals_user_id'), 'action_proposals', ['user_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=False),
    sa.Column('prep_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_event_user_external')
    )
    op.create_index(op.f('ix_calendar_events_external_id'), 'calendar_events', ['external_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_time'), 'calendar_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_table('commitments',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=16), nullable=False),
    sa.Column('counterparty', sa.String(length=320), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_source_id'), 'commitments', ['source_id'], unique=False)
    op.create_index(op.f('ix_commitments_user_id'), 'commitments', ['user_id'], unique=False)
    op.create_table('connected_accounts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_account_email', sa.String(length=320), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('token_ciphertext', sa.Text(), nullable=False),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_accounts_user_id'), 'connected_accounts', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body_summary', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classification', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_message_user_external')
    )
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    op.create_index(op.f('ix_messages_thread_id'), 'messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_source_id'), 'tasks', ['source_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('draft_replies',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('gmail_draft_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_replies_message_id'), 'draft_replies', ['message_id'], unique=False)
    op.create_index(op.f('ix_draft_replies_user_id'), 'draft_replies', ['user_id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action_proposal_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rollback_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_proposal_id'], ['action_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_action_proposal_id'), 'execution_logs', ['action_proposal_id'], unique=False)
    op.create_index(op.f('ix_execution_logs_user_id'), 'execution_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_logs_user_id'), table_name='execution_logs')
    op.drop_index(op.f('ix_execution_logs_action_proposal_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_draft_replies_user_id'), table_name='draft_replies')
    op.drop_index(op.f('ix_draft_replies_message_id'), table_name='draft_replies')
    op.drop_table('draft_replies')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_thread_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_connected_accounts_user_id'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    op.drop_index(op.f('ix_commitments_user_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_source_id'), table_name='commitments')
    op.drop_table('commitments')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_time'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_external_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_action_proposals_user_id'), table_name='action_proposals')
    op.drop_table('action_proposals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
