"""add commitment.from_automated

Revision ID: ceed65a3499b
Revises: 784d448bdd7c
Create Date: 2026-05-21 23:46:30.928769
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ceed65a3499b"
down_revision: str | None = "784d448bdd7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default backfills existing rows as not-automated; the app sets the value
    # explicitly on new rows. Drop the server default afterward so the column is purely
    # application-managed going forward.
    op.add_column(
        "commitments",
        sa.Column("from_automated", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("commitments", "from_automated", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("commitments", "from_automated")
    # ### end Alembic commands ###
